# Generated by Django 4.0 on 2022-01-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_car_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
