# Generated by Django 4.0 on 2022-01-05 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_carimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='title',
            new_name='producer',
        ),
        migrations.RemoveField(
            model_name='car',
            name='thumbnail',
        ),
    ]
