# Generated by Django 4.0 on 2022-01-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_title_car_producer_remove_car_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='number_of_doors',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='production_year',
            field=models.CharField(max_length=10),
        ),
    ]
